### Get all poems
GET {{URL}}

### Get poem by id 1
GET {{URL}}/1

### Create poem 1
POST {{URL}}
Content-Type: application/json

{
  "author": "Robert Frost",
  "title": "Nothing Gold Can Stay",
  "type": "SHORT_POEM",
  "poem": "Nature's first green is gold,\nHer hardest hue to hold.\nHer early leaf's a flower, \nBut only so an hour."
}

### Create poem 2

POST {{URL}}
Content-Type: application/json

{
  "author": "Ella Wheeler Wilcox",
  "title": "A Fallen Leaf",
  "type": "SHORT_POEM",
  "poem": "A trusting little leaf of green. \nA bold audacious frost. \nA rendezvous, a kiss or two. \nAnd youth for ever lost."
}

### Create poem 3

POST {{URL}}
Content-Type: application/json

{
  "author": "Shel Silverstein",
  "title": "Underface",
  "type": "SHORT_POEM",
  "poem": "Underneath my outside face. \nThere's a face that none can see. \nA little less smiley, \nA little less sure."
}

### Update poem
PUT {{URL}}/2
Content-Type: application/json

{
  "type": "HAIKU"
}

### Delete poem by id (3)

DELETE {{URL}}/3